version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/fixtures/maven"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/fixtures/gradle"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
