import { describe, it, expect } from 'vitest'
import { parseProperties } from '../src/properties.js'

describe('parseProperties', () => {
  it('reads keys with escaped separators, as in Maven module keys', () => {
    const properties = parseProperties(
      'org.example\\:app.sonar.sources=/work/app/src\n'
    )
    expect(properties.get('org.example:app.sonar.sources')).toBe(
      '/work/app/src'
    )
  })

  it('unescapes values the way Properties.store writes them', () => {
    const properties = parseProperties(
      'url=http\\://host\\:9000\npath=C\\:\\\\dir\nname=Caf\\u00e9\ntabs=a\\tb\n'
    )
    expect(properties.get('url')).toBe('http://host:9000')
    expect(properties.get('path')).toBe('C:\\dir')
    expect(properties.get('name')).toBe('Café')
    expect(properties.get('tabs')).toBe('a\tb')
  })

  it('accepts every separator and skips comments and blank lines', () => {
    const properties = parseProperties(
      '#Generated by a SonarScanner\n! other comment\n\na=1\nb: 2\nc 3\n  d = 4\n'
    )
    expect([...properties]).toEqual([
      ['a', '1'],
      ['b', '2'],
      ['c', '3'],
      ['d', '4']
    ])
  })

  it('joins continuation lines', () => {
    const properties = parseProperties('list=a,\\\n    b,\\\n    c\nnext=1\n')
    expect(properties.get('list')).toBe('a,b,c')
    expect(properties.get('next')).toBe('1')
  })

  it('does not treat an escaped trailing backslash as a continuation', () => {
    const properties = parseProperties('dir=C\\:\\\\\nnext=1\n')
    expect(properties.get('dir')).toBe('C:\\')
    expect(properties.get('next')).toBe('1')
  })

  it('keeps empty values', () => {
    expect(parseProperties('sonar.sources=\n').get('sonar.sources')).toBe('')
  })
})
